name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Criar arquivo .env
        run: |
          echo "REACT_APP_FIREBASE_CONFIG='${{ secrets.REACT_APP_FIREBASE_CONFIG }}'" >> .env
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_REGISTRATION_SYSTEM_203C8 }}
          channelId: live
          projectId: registration-system-203c8
